### ISSUE TITLE
Create the TimeClock

### ISSUE THREAD

**Issue by braddoeswebdev** [GatherPack/gatherpack#105]
People need a way to keep track of their time in a structured way. 

A `TimeClockPeriod` will hold many `TimeClockPunches` (I'm not in love with the naming there & am open to suggestions) and represent something like a pay period, an FRC build season, or any other structured bucket into which people might want to log & report time.

A `TimeClockPeriod` will be a scaffold-ish structure with a name, start & end times, a field for determining who can create/update associated `TimeClockPunches` (only admins, admins + managers, anybody), and optionally belong_to a `Team`. Only admins & `Team` managers should be able to create `TimeClockPeriods`

A `TimeClockPunch` will have a start & end time, belong to a `Person`, and optionally belong to a `TimeClockPeriod`. Anybody should be able to create `TimeClockPunches` but the ability to associate them with any given `TimeClockPeriod` should be limited by the field on the `TimeClockPeriod`. Additionally, only admins & managers should be able to create or update `TimeClockPunches` for people other than themselves.

**Comment by ez500** [comment]
How was this implemented last time (current BackOffice) in terms of views and how TimeClockPeriod affected everyone's hours at a certain time?

**Comment by braddoeswebdev** [comment]
TimeClockPeriods aren't a thing in BackOffice - Punches just have a string field that stores what it's for (meeting, outreach, etc). Having an actual model for that will allow for easier reporting, better control over who can report certain kinds of time, and maybe eventually smarter behavior in the kiosk.

**Comment by ez500** [comment]
So, would a TimeClockPeriod be a period as in time of day, or from mm/dd/yyyy to mm/dd/yyyy? Also, would any TimeClockPunches that are clocked in automatically belong to the instance of TimeClockPeriod that would be currently active?

**Comment by ez500** [comment]
**Brad's answer:**

A TimeClockPeriod for us would be "meeting" or "outreach" - it's just a bucket into which you can dump time records. 

Something like that, yes - or if there's ambiguity about which period to use, the kiosk could prompt the user to select one. We will eventually want to look at building some additional smarts in the kiosk to look at events & teams & stuff to help figure that out too.
