### ISSUE TITLE
Add `CheckinFields` and `CheckinFieldResponses`

### ISSUE THREAD

**Issue by braddoeswebdev** [GatherPack/gatherpack#152]
(i.e. Travel Events would have CheckinFields like "Hotel Room" and "Transportation")

A `CheckinField` should be a scaffold-ish thing that belongs to an `EventType` and has a name & a permission selector to restrict who can create/update related `CheckinFieldResponses`.

A `CheckinFieldResponse` should be a model that belongs to a `Checkin` and a `CheckinField` and store a value for that field, and should be created/updated in-line with creating/updating the `Checkin`.

**Comment by Gerseneck** [comment]
TODO:
- [ ] fix checkin breadcrumbs
- [ ] fix checkin save
- [ ] finish permissions
- [ ] better routing
