### ISSUE TITLE
Implement Audit Logging & Versioning

### ISSUE THREAD

**Issue by braddoeswebdev** [GatherPack/gatherpack#19]
We should add some sort of mechanism to track all of the things that happen within the system & the ability to undo changes & accidental deletions (ask me how I know we should really do that...) and such.

[Papertrail](https://github.com/paper-trail-gem/paper_trail) is typically the go-to library for this.

We should look at shoving all of the records for this into a separate database.

**Comment by Gerseneck** [comment]
TODO:
- [ ] figure out why reify doesn't work sometimes
- [ ] search for audit log dates?
- [ ] pundit policies
