### ISSUE TITLE
Implement nicer code editor

### ISSUE THREAD

**Issue by braddoeswebdev** [GatherPack/gatherpack#22]
When working on hooks / reports / pages, it would be lovely to have something a little higher quality to work in than the standard textarea control.

**Comment by Gerseneck** [comment]
I found a couple of embedded code editors that we could work with yesterday:
- [CodeJar](https://medv.io/codejar/)
- [AceJs](https://ace.c9.io/)

CodeJar is more minimal and looks better, but AceJs has a lot more features. I haven't tested any of these out yet so I don't know how any of the specifics work.

**Comment by braddoeswebdev** [comment]
I tried both of these out, couldn't get Ace to work at all & Codejar did better but still had some issues - like the auto-closing pairs made your cursor disappear. Also looked in to using Monaco, which is the editor component from VS Code, but it is really not mobile-friendly at all.

More research needed!

**Comment by codemob-dev** [comment]
[CodeMirror](https://codemirror.net/) is another possibility.
